### PR TITLE
feat: implement dynamic visibility for stats and avatar via `hide` parameter

### PR DESCRIPTION
**Pull request by liby**
## Context

https://github.com/LuciNyan/pixel-profile/pull/3#issuecomment-1962804640

## Screenshots

1. `&hide=avatar`

    image

2. `&hide=avatar,commits`

    image

3. `&hide=avatar,commits,rank,stars`

    image

4. `&hide=commits,rank`

    image

5. `&hide=commits,contributions,issues,prs,stars`

    image

The display seems a bit odd in extreme cases (I think few people would do this). Do you have any thoughts? You can push changes directly to my PR.

### CODE REVIEW

**Comment by LuciNyan** [comment]
Wow, awesome job on this! 😍 Your code is really well-structured and easy to read. Only thing I noticed 💅🏻 - when a pic and line are together, the line length seems a little off. Not sure if an enum is the way to go for defining the dash count in each case?

Overall really appreciate you taking the time to contribute! ❤️  Let's think if there's another way to handle this besides enums.

image
image

**Comment by liby** [comment]
I've noticed that the dynamic height adjustment logic based on the number of visible items seems to be causing the separator line to resize itself, which results in inconsistent lengths across different card states:
```
  const visibleStatsCount = getVisibleStatsCount(hiddenStatsKeys)
  const hiddenStatsCount = statsToConsider.length - visibleStatsCount
  const baseCardSize = rank ? CARD_SIZE.BIG : CARD_SIZE.SMALL

  const HEIGHT_DECREASE_PER_HIDDEN_STAT = 20
  const dynamicHeight = baseCardSize.CARD_HEIGHT - hiddenStatsCount * HEIGHT_DECREASE_PER_HIDDEN_STAT
```

By removing this logic and fixing the card height, the separator line's length seems to stay constant, regardless of the number of stats displayed(except for hidden avatars). I've taken some screenshots for comparison. Do you think fixing the card height would be a good solution to maintain a consistent separator line length?

image

image

image

**Comment by LuciNyan** [comment]
(┌・ω・)┌✧  Give me a sec, I'm playing around with some different ideas hhh

**Comment by LuciNyan** [comment]
(┌・ω・)┌✧ Give me a sec, I'm playing around with some different ideas hhh.

**Comment by LuciNyan** [comment]
Sorry for the delay! 😞 I tried a few different approaches but your implementation looks like the best solution so far. Thanks so much for the PR, @liby! <3

**Pull request merged**
